import Head from 'next/head';
import type { NextPage } from 'next';
import { Banner } from '../components/Banner';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>WorldTrip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />

      <main>
        HOME PAGE
      </main>
    </div>
  );
};

export default Home;
